# Copyright 2022 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build eyelash_sofle'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["eyelash_sofle_left nice_view_adapter nice_view","eyelash_sofle_right nice_view_adapter nice_view"]'
